### ISSUE TITLE
Error while adding flows to namespace in ceph-integration

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#158]
With latest commons:master, while starting the `ceph-integration` it shows the below stack trace

```
Traceback (most recent call last):
  File "/usr/bin/tendrl-ceph-integration", line 11, in <module>
    load_entry_point('tendrl-ceph-integration==1.2', 'console_scripts', 'tendrl-ceph-integration')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/tendrl_ceph_integration-1.2-py2.7.egg/tendrl/ceph_integration/__init__.py", line 45, in <module>
    CephIntegrationNS()
  File "/usr/lib/python2.7/site-packages/tendrl_ceph_integration-1.2-py2.7.egg/tendrl/ceph_integration/__init__.py", line 43, in __init__
    super(CephIntegrationNS, self).__init__()
  File "/usr/lib/python2.7/site-packages/tendrl_commons-1.2-py2.7.egg/tendrl/commons/__init__.py", line 27, in __init__
    self.register_subclasses_to_ns()
  File "/usr/lib/python2.7/site-packages/tendrl_commons-1.2-py2.7.egg/tendrl/commons/__init__.py", line 144, in register_subclasses_to_ns
    self.add_obj_flow(flow_cls[1].obj.__name__,
AttributeError: type object 'CephIntegrationBaseFlow' has no attribute 'obj'
```

Seems to be some small change required in BaseFlow definition, but not sure what.

**Comment by shtripat** [comment]
This was issue with branch. Once `master` selected no issues. Closing now.
